### ISSUE TITLE
Includere Italia Design Kit

### ISSUE THREAD

**Issue by jdeyla** [CodeAtCode/design-wordpress-theme#1]
Ciao,
ovviamente grazie per questo progetto, ma vi scrivo perchè non capisco come utilizzarlo.
Ho seguito i passi per l'installazione, ma l'html resta svestito, e non so perchè.

Ammetto di essere assolutamente a digiuno di Gulp e NPM ecc, ma penso di aver fatto tutti i passaggi e ancora non vedo effetti.

E' come se il CSS fosse quello del Kit, ma l'html no, possibile? 

Ho dato uno sguardo veloce, ma se guardo ad esempio gli skiplink all'inizio del codice, nel CSS del tema la regola chiama .Skiplinks ma nell'html vedo "skip-link screen-reader-text"

grazie

**Comment by Mte90** [comment]
Ciao puoi spiegarti meglio con degli screenshot?
Probabilmente non ti carica il css.

**Comment by jdeyla** [comment]
Grazie. La testata, in backoffice è questa, e se prendo le classi degli skiplink sono quelle che ho detto io.
 il css nel tema mi pare lo carichi
<img width="900" alt="css" src="https://user-images.githubusercontent.com/832590/39121553-48f31db0-46f2-11e8-86f8-5b685084890a.png">

ma non  vedo effetti, ad esempio sulla barra del brand
<img width="1152" alt="no effetti" src="https://user-images.githubusercontent.com/832590/39121667-95620f26-46f2-11e8-9f06-f4b25032b737.png">

**Comment by jdeyla** [comment]
Magari sbaglio io che ho l'aspettativa di trovarmi un tema che è il kit: già con lo spazio per il link all'amministrazone superiore nella testata, il brand e tutto quel che ne segue.

**Comment by Mte90** [comment]
Da quello che vedo il tema è ancora incompleto, carica solamente il file css di base di bootstrap senza colori o altri.
@EugenioPetulla ne sa di più visto che ci stava lavorando lui.

**Comment by jdeyla** [comment]
Grazie. 
Perchè mi pare di aver seguito le istruzioni, Con Docker non ho provato. Uso MAMP che è più semplice, con le sue porte di default (8888)
Ho una installazione locale quindi e nella cartella del tema, ho clonato il repository GIT.  
Ho cambiato la porta in Gulp.js in modo che Gulp faccia il suo lavoro: sembra che lo faccia in effetti e quando chiamo localhost:3000/wp (la mia directory locale), lavora e mi porta sulla 8888

Da terminale ìi file sass dice che li compila, ... ma non mi pare che l'html non li richiami da nessuna parte.

**Comment by Mte90** [comment]
Hanno realizzato un altro fork che é piú avanti di questo progetto.
